import Head from "next/head";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";

const Layout = ({ children, metaTitle, metaDescription }) => {
  return (
    <>
      <Head>
        <title>{`Projek NextJs - ${metaTitle}`}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-row">
        <Sidebar />
        {children}
      </div>
      <Footer />
    </>
  );
};
export default Layout;
